#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"

case $1 in
$SERVICE_NAME:link)
	APP=$2
	verify_app_name "$APP"
	dokku_log_info1 "Linking mailservice to $APP..."
	dokku docker-options:add "$APP" deploy "--link $SERVICE_NAME:$SERVICE_NAME"
	dokku config:set --no-restart "$APP" MAILSERVICE_HOST=mailservice
	dokku config:set "$APP" MAILSERVICE_PORT=25
	;;
$SERVICE_NAME*)
	cat << HELP
Usage: dokku mailservice[:COMMAND]

Manage the running mailservice instance

Commands:
    mailservice:link <app>        Makes mailservice available in the specified app
    mailservice:unlink <app>      Removes a previously created link
    mailservice:get_dns_config    Get the DNS config needed to set up SPF, DKIM & rDNS
HELP
	;;
esac
